### PR TITLE
Mapping redesign

### PR DESCRIPTION
**Pull request by azahnen**
- This is not ready for merging yet, it has to be cleaned up first.
- Startup might be slower since currently the old schema derivers are still executed in addition to the new ones.
- This is ready for testing, the redesign of the query generation steps is complete.
- One thing I found during testing is that queryables and sortables for coretable JSON properties, which were introduced in #197, do not work in master, most likely since #284. That should work again on this branch.

### CODE REVIEW

**Comment by azahnen** [comment]
@cportele 
Scopes were not really considered yet, `planid` should work as expected now. I have not looked at the XTrasse example yet, but if it does not use scopes, it has a different cause.

Another thing I noticed is that the responses for XPlan are slightly different. For example `BP_BaugebietsTeilFlaeche` on this branch is missing `zusatzkontingentFlaeche`, instead it has `wirdAusgeglichenDurchABE`.  My feeling is that both variants on master and this branch are wrong, it should have both properties and maybe even more. I think there is a seemingly random logic based on query order because there are still some places where only the table name without filters is considered.

**Comment by azahnen** [comment]
@cportele The XTrasse example should work as well now.

**Comment by azahnen** [comment]
@cportele The issue with `geoval` should be fixed. The issue with `wfs-nrw` is unrelated, it also occurs on master.

**Comment by azahnen** [comment]
@cportele The issue with`observation` should be fixed.

**Comment by cportele** [comment]
@azahnen - Yes, all known issues are now fixed.

As a aside, I now get WARN messages during startup, which I think is the result of dependency upgrades (there are also new INFO messages). The warning is: "A provider de.ii.xtraplatform.ops.app.OpsRequestDispatcherImpl registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider de.ii.xtraplatform.ops.app.OpsRequestDispatcherImpl will be ignored."

**Comment by azahnen** [comment]
@cportele 
That is because in `geoval` the main log level is set to `INFO` and in the development environment `showThirdPartyLoggers` is on by default. 
You would not see this for example in `demo` where the main log level is set to `OFF`.
As for the warning itself, it works as expected, so I don't think there is any need for action.

**Comment by azahnen** [comment]
@cportele 
The issue with `BP_Bereich` should be fixed.

**Comment by cportele** [comment]
Yes, it works now.

**Comment by cportele** [comment]
@azahnen 

Configuration: `embed`
Request: http://localhost:7080/strassen/collections/unfaelle/items/1?f=json 

The request now returns only a single item in `#/properties/abs/properties/unfaelle`, but it should include all accidents on the road segment. I suspect this is the result of the changes in this PR (tested with the "next" image).

**Comment by azahnen** [comment]
@cportele 
The issue with `embed` should be fixed.
